# SPDX-License-Identifier: GPL-2.0
obj-y	+= goodix_gt9xx.o
CFLAGS = -std=c99
ccflags-y := -std=gnu99 -Wno-declaration-after-statement
ccflags-y += -Wno-unused-variable -Wno-unused-function

goodix_gt9xx-y		+=goodix_tool.o
goodix_gt9xx-y		+=gt9xx.o
goodix_gt9xx-y		+=gt9xx_update.o
